## Check GPU (if connected)

In [27]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Import pytorch

In [28]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### **Definition**: A tensor is a generalization of scalars, vectors, and matrices to any number of dimensions, used to represent multi-dimensional data or relationships

### Scalar -> 0-D tensor (just a number)
### Vector -> 1-D tensor
### Matrix -> 2-D tensor
### Tensor -> n-D array (where n > 2)



### **Creating a tensor**



Pytorch tensors are created using 'torch.Tensor()'

1.) scalar

In [29]:
#create and initialize scalar
scalar = torch.tensor(7)

scalar


tensor(7)

In [30]:
#Check dimension of scalar (expecting a 0)
scalar.ndim

0

In [31]:
#Get tensor back as int
scalar.item()

7

2.) vector

In [32]:
#create and initialize vector
vector = torch.tensor([1,2,3])

vector

tensor([1, 2, 3])

In [33]:
#Check dimension of scalar (expecting a 1)
vector.ndim

1

In [34]:
#Check how many items we have in vector
vector.shape

torch.Size([3])

3.) matrix

In [35]:
#create and intialize matrix
MATRIX = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

4.) tensor

In [36]:
#Create tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [37]:
#Check dimension
TENSOR.ndim

3

In [38]:
#Check shape of tensor
TENSOR.shape

torch.Size([1, 3, 3])

Note that when we run `TENSOR.shape` , we see that its 1 x 3 x 3. Lets look at what that means

In [39]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Typically, notation for these are as followed:

-> a = scalar

-> y = vector

-> Q = matrix

-> X = tensor

###**Random Tensors**

####Random tensors are important because the way many neural networks learn is by starting with tensors full of random numbers and then adjust those random numbers to better represent the data

####`Start with random numbers -> look at data -> update random numbers -> look at data -> ...