## Check GPU (if connected)

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Import pytorch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### **Definition**: A tensor is a generalization of scalars, vectors, and matrices to any number of dimensions, used to represent multi-dimensional data or relationships

### Scalar -> 0-D tensor (just a number)
### Vector -> 1-D tensor
### Matrix -> 2-D tensor
### Tensor -> n-D array (where n > 2)



### **Creating a tensor**



Pytorch tensors are created using 'torch.Tensor()'

1.) scalar

In [3]:
#create and initialize scalar
scalar = torch.tensor(7)

scalar


tensor(7)

In [4]:
#Check dimension of scalar (expecting a 0)
scalar.ndim

0

In [5]:
#Get tensor back as int
scalar.item()

7

2.) vector

In [6]:
#create and initialize vector
vector = torch.tensor([1,2,3])

vector

tensor([1, 2, 3])

In [7]:
#Check dimension of scalar (expecting a 1)
vector.ndim

1

In [8]:
#Check how many items we have in vector
vector.shape

torch.Size([3])

3.) matrix

In [9]:
#create and intialize matrix
MATRIX = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

4.) tensor

In [10]:
#Create tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
#Check dimension
TENSOR.ndim

3

In [12]:
#Check shape of tensor
TENSOR.shape

torch.Size([1, 3, 3])

Note that when we run `TENSOR.shape` , we see that its 1 x 3 x 3. Lets look at what that means

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Typically, notation for these are as followed:

-> a = scalar

-> y = vector

-> Q = matrix

-> X = tensor

###**Random Tensors**

####Random tensors are important because the way many neural networks learn is by starting with tensors full of random numbers and then adjust those random numbers to better represent the data

####`Start with random numbers -> look at data -> update random numbers -> look at data -> ...

In [14]:
#Create random tensor of size (5,9)

rand_tensor2d = torch.rand(5,9)

rand_tensor2d

tensor([[0.2924, 0.7573, 0.7256, 0.5883, 0.3344, 0.0012, 0.3872, 0.6573, 0.4106],
        [0.0180, 0.1247, 0.8800, 0.3264, 0.0279, 0.9162, 0.4524, 0.2895, 0.9785],
        [0.9512, 0.1226, 0.6811, 0.8880, 0.5808, 0.9023, 0.8703, 0.9191, 0.2311],
        [0.1642, 0.9304, 0.9234, 0.5516, 0.5051, 0.3440, 0.2566, 0.3764, 0.4050],
        [0.3709, 0.3170, 0.6107, 0.1214, 0.3145, 0.8904, 0.6229, 0.1351, 0.3730]])

In [15]:
#Create random tensor of size (2,3,3)

rand_tensor3d = torch.rand(3,3,3)

rand_tensor3d

tensor([[[0.0965, 0.0890, 0.2679],
         [0.9869, 0.2646, 0.3593],
         [0.1087, 0.8960, 0.0131]],

        [[0.8380, 0.8863, 0.8520],
         [0.8446, 0.3287, 0.0230],
         [0.7758, 0.3806, 0.8042]],

        [[0.4987, 0.1911, 0.4697],
         [0.7312, 0.9580, 0.6630],
         [0.7882, 0.2988, 0.8985]]])

###Tensor datatypes

####**Note**: Tensor datatypes are one of 3 big inevitable errors with Pytorch and Deep learning

1. Tensor is not right datatype (working with float32 and float 16 data)
2. Tensor is not right shape (multiplying two matrices that aren't compatible)
3. Tensor is not on right device (tensor can be on cpu and gpu)

In [16]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0] , dtype = None, device = "cpu", requires_grad = False)

#Print values and type
float_32_tensor , float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [17]:
#Convert to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
#The following works because PyTorch handles thiseerror behind the scenes.
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [19]:
##Getting information from tensors

#Tensor is not right datatype (working with float32 and float 16 data)
# -> use tensor.dtype to get data type of tensor
#Tensor is not right shape (multiplying two matrices that aren't compatible)
# -> use tensor.shape to get shape of tensor
#Tensor is not on right device (tensor can be on cpu and gpu)
# -> use tensor.device to check if tensor is on gpu or cpu

###Manipualting tensors (tensor operations)

1.) Addition

2.) Subtraction

3.) Multiplication (element-wise)

4.) Division

5.) Matrix multiplication

In [20]:
#Create tensor for operation

tensor_operation_test = torch.tensor([1,2,3])

In [21]:
#Adding to tensor (same as subtract)
tensor_operation_test + 10

tensor([11, 12, 13])

In [22]:
#Multiplying tensor (aka scaling) (same as dividing)
tensor_operation_test * 3

tensor([3, 6, 9])

In [23]:
#Matrix multiplication
tensor_operation_test * tensor_operation_test

tensor([1, 4, 9])

In [24]:
#Dot product
torch.matmul(tensor_operation_test,tensor_operation_test)

tensor(14)

*Note: some built-in functions run faster than using operands like *,+,-, etc.

For matrix multiplication:

1.) Inner dimnensions must match
* matmul.(3,2) , (3,2) won't work
* matmul.(3,2) , (2,3) will work

2.) Resulting shape will be the outer dimensions

In [34]:
## Finding min,max,mean,sum,etc. (Tensor aggregation)

x = torch.arange(0,100,10)

min = torch.min(x)
max = torch.max(x)

print(min)
print(max)

#Torch.mean requires tensor of float32
mean = torch.mean(x.type(torch.float32))

print(mean)

sum = torch.sum(x)

print(sum)

##Find index in tensor that has min/max value

x.argmin(), x.argmax()

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


(tensor(0), tensor(9))